### PR TITLE
feat: 代码合并、dde接口适配

### PR DESCRIPTION
**Pull request by feeengli**
合并release/eagle修改到master，V23 dde新接口适配

Log: 合并release/eagle修改到master，V23 dde新接口适配

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
