### PR TITLE
fix:  修复平均负载展示的指标值与实际查询的值相一致

### PR DESCRIPTION
**Pull request by jeffshuai**
修复平均负载展示的指标值与实际查询的值相一致

Log:  修复平均负载展示的指标值与实际查询的值相一致

Bug: https://pms.uniontech.com/bug-view-250027.html

### CODE REVIEW

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]

**Pull request merged**
