### PR TITLE
fix: remove unused libprocps dependency

### PR DESCRIPTION
**Pull request by felixonmars**
It doesn't seem to be used at all.

### CODE REVIEW

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-system-monitor/commit/ce8ab16d43d9f4e17b63405cbdfe79c9d4e9437d

看上去维护团队自己做了这个修改... 😂

**Comment by felixonmars** [comment]
……这个pgw判断是啥意思

**Comment by Aleksanaa** [comment]
arch repo这边应该也要去掉

**Comment by Rabenda** [comment]
> ……这个pgw判断是啥意思

华为特定机型 盘古w系列

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-system-monitor/pull/260#issuecomment-1612662398 根据之前的结论，应该不用合了

**Pull request closed without merging**
