### PR TITLE
fix: CPU磁盘网络界面文字和间距

### PR DESCRIPTION
**Pull request by wyu71**
调整CPU磁盘网络界面文字和间距

Log: 正确显示CPU磁盘网络界面文字和间距
Bug: https://pms.uniontech.com/bug-view-157227.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
