### PR TITLE
fix: 修复1060末启动server

### PR DESCRIPTION
**Pull request by jeffshuai**
修复1060因deepin-service-manager不启动server

Log: 修复1060因deepin-service-manager不启动server

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
