### PR TITLE
fix: 合入release/eagle修改，兼容V20与V23

### PR DESCRIPTION
**Pull request by feeengli**
合入release/eagle修改，兼容V20与V23

Log: 合入release/eagle修改，兼容V20与V23

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
