### PR TITLE
fix: 系统监视器修改进程优先级后重新查看优先级始终显示为19

### PR DESCRIPTION
**Pull request by wyu71**
增加读取优先级值接口

Log: 正确显示优先级
Bug: https://pms.uniontech.com/bug-view-166309.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
