### PR TITLE
fix: Adapt displayjack lib getWindowStatesList() interface

### PR DESCRIPTION
**Pull request by starhcq**
Adapt displayjack lib getWindowStatesList() interface

Log: Adapt displayjack lib getWindowStatesList() interface
Bug: https://pms.uniontech.com/bug-view-235483.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
