### PR TITLE
fix: Add DBus interface to enable service

### PR DESCRIPTION
**Pull request by rb-union**
非开发者模式下设置systemd服务失败(cli同样)
调整非开发者模式下的服务设置方式，改由后端
服务执行

Log: 修复设置服务启动方式失败问题
Bug: https://pms.uniontech.com/bug-view-241793.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by pengfeixx — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
