### PR TITLE
fix: 文管在系统监视器中进程中图标显示错误

### PR DESCRIPTION
**Pull request by wyu71**
过滤部分文管的desktop

Log: 正常显示文管图标
Bug: https://pms.uniontech.com/bug-view-160309.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — APPROVED** [review]
/+1

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
