### PR TITLE
fix: 同步 进程结束数据上报 代码

### PR DESCRIPTION
**Pull request by feeengli**
添加进程结束数据上报

Log: 添加进程结束数据上报

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by hundundadi** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
