### PR TITLE
fix: quickpannel start app and disappeared self auto

### PR DESCRIPTION
**Pull request by jeffshuai**
快捷面板启动应用系统监示器后快捷面板自动隐藏

Log: quickpannel start app and disappeared self auto

Bug: https://pms.uniontech.com/bug-view-228255.html
Bug: https://pms.uniontech.com/bug-view-228257.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
