### PR TITLE
fix: wayland下系统监视器打不开和去掉插件是否可用

### PR DESCRIPTION
**Pull request by wyu71**
wayland下系统监视器打不开和去掉插件是否可用

Log: wayland下系统监视器打不开
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
