### PR TITLE
chore: Update version to 6.0.12

### PR DESCRIPTION
**Pull request by starhcq**
Update version to 6.0.12
  相关PR:
  * #306

Log: Update version to 6.0.12

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by feeengli** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
