### PR TITLE
fix: 通过统信UOS助手启动文管在系统监视器中进程中图标显示错误

### PR DESCRIPTION
**Pull request by wyu71**
识别UOS助手启动插件

Log: 正常显示文管图标
Bug: https://pms.uniontech.com/bug-view-160309.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
