### PR TITLE
fix: 更新popup的dbus

### PR DESCRIPTION
**Pull request by wyu71**
更新popup的dbus

Log: 显示popup界面
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
