### PR TITLE
fix: 进程列表中上传下载列数据始终为0

### PR DESCRIPTION
**Pull request by wyu71**
多网卡时未选择默认网卡

Log: 正常显示应用网速
Bug: https://pms.uniontech.com/bug-view-163621.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
