### PR TITLE
feat: Add build flag to disable wayland support

### PR DESCRIPTION
**Pull request by wineee**
fix: No such file "KWayland/Client/clientmanagement.h"
Bug: https://github.com/linuxdeepin/developer-center/issues/2239

### CODE REVIEW

**Comment by yorcan** [comment]
> 

it does not support in common environment with kwayland to build this project.
There are two suggest to build:
1.checkout the maintain/1042
2.install the new 1050 environment->sudo apt-get dist-upgrade
Follow this source.list to update it before.
if you have UOS system.
## Generated by deepin-installer
deb https://professional-packages.chinauos.com/desktop-professional eagle main contrib non-free
deb-src https://professional-packages.chinauos.com/desktop-professional eagle main contrib non-free
deb http://pools.uniontech.com/desktop-professional eagle main contrib non-free
deb http://pools.uniontech.com/ppa/dde-eagle eagle/1050 main contrib non-free
deb [trusted=yes] http://10.0.36.228/uos-professional/repo/professional/ eagle/1050 main contrib non-free
deb [trusted=yes] http://aptly.uniontech.com/pkg/eagle-1050/release-candidate/5LiT5Lia54mIMTA1MOaMgee7rembhuaIkOS4u-mimDIwMjEtMTAtMDkgMDk6NDY6MzQ unstable main

**Comment by yorcan** [comment]
Please send email to lishiqi@uniontech.com to merge this change pls.

**Comment by wineee** [comment]
> it does not support in common environment with kwayland to build this project.

Does deepin-system-monitor depend on a non-free project? Will dde support wayland on other distributions？ I use ArchLinux

**Comment by wineee** [comment]
> Please send email to [lishiqi@uniontech.com](mailto:lishiqi@uniontech.com) to merge this change pls.

Just use https://github.com/linuxdeepin/deepin-system-monitor/commit/21f913c1b72829208b62b1f2233485c0ceb82e0a.patch

**Comment by yorcan** [comment]
> > it does not support in common environment with kwayland to build this project.
> 
> Does deepin-system-monitor depend on a non-free project? Will dde support wayland on other distributions？ I use ArchLinux

dde support kwayland ,however the header <clientmanagement.h> of kwayland was modified by uos team.
we will merge this change and notify us.
thank you wineee.

**Comment by RiskVirusPro** [comment]
http://aptly.uniontech.com/pkg/eagle-1050/release-candidate/56qX5Y-j566h55CG5ZmoR2Vycml06ZuG5oiQ5LiT55So5LuT5bqTMjAyMS0xMS0xMiAxNjoxNTozNA unstable/main amd64 Packages

**Comment by wineee** [comment]
This patch didn‘t enable `WAYLAND_SESSION_TYPE`  by defaul. If `WAYLAND_SESSION_TYPE` is defined, there should be no any change in the code.

**Comment by wineee** [comment]
>  as a result of the $XDG_SESSION_TYPE requires a display session but none would be supplied.

Probably because WAYLAND_SESSION_TYPE is a special value, I create a new patch and make `WAYLAND_SESSION_SUPPORT` defined by defaul

https://github.com/linuxdeepin/deepin-system-monitor/commit/36dc3291fd45810310c3fdaeb33e493ae6433778.patch

**Comment by RiskVirusPro** [comment]
> > as a result of the $XDG_SESSION_TYPE requires a display session but none would be supplied.
> 
> Probably because WAYLAND_SESSION_TYPE is a special value, I create a new patch and make `WAYLAND_SESSION_SUPPORT` defined by defaul
> 
> https://github.com/linuxdeepin/deepin-system-monitor/commit/36dc3291fd45810310c3fdaeb33e493ae6433778.patch

you may try dpkg-buildpackage command on a non-session environment to see if the .deb package works well on a wayland session type desktop, it didn't work well last time...

**Comment by RiskVirusPro** [comment]
The main issue is we have to make sure the same .deb package works both on x11 and wayland.

**Comment by wineee** [comment]
> We depend on libkf5wayland-dev package to support wayland protocol. Due to technology updating day by date ,this package differs from version to version, which also developed by our colleages responding for Wayland adaptation. 

Which exactly version of libkf5wayland-dev do you using?

**Comment by RiskVirusPro** [comment]
> 

4:5.57.0.14-1+eagle for now

**Comment by felixonmars** [comment]
Any idea why this is closed? We still need it for building on Arch Linux and probably also other distros.

**Comment by wineee** [comment]
> Any idea why this is closed? We still need it for building on Arch Linux and probably also other distros.

 Continue work in https://github.com/linuxdeepin/deepin-system-monitor/pull/161

**Pull request closed without merging**
