### PR TITLE
fix: 当CPU或内存占用过高时无法点击通知查看系统监视器

### PR DESCRIPTION
**Pull request by wyu71**
dde的Notification参数错误

Log: 正确启动系统监视器
/review @lzwind @HeeMingYang @feeengli @hundundadi @myk1343

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
