### PR TITLE
fix: build failures with Qt 5.15+

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by z966768** [comment]
it will be modified in the following optimization

**Comment by felixonmars** [comment]
More and more files are affected now. Any progress on the optimization?

**Comment by z966768** [comment]
what you mean by 'optimization'? If you're referring performance, it's alread been done months ago.
build failure issues are not a concern right now, because of different build envs, plus PJ are  still on heavy development. only bugs are appreciated for now.
Please make a patch by yourself if any of those missing #include errors encountered.
most sources (GUI parts) under ROOT src dir will be replaced by a new design implemention in a late time (QGraphisView Framework)

**Comment by felixonmars** [comment]
'optimization' was your original word in the last comment (14 days ago as of today). I made a patch by myself as you said, and submitted right here, yet two months later you are telling me my efforts on keeping all these software build-able on Arch (and also Debian, Fedora, Gentoo, Ubuntu, ...) "not a concern".

@xmuli @hualet @zccrs Please, do not make this more frustrated than needed.

**Comment by sequencer** [comment]
I think it is a right time to drop support to software like this. or move to AUR maintained by vendor.

**Comment by sequencer** [comment]
I think it is a right time to drop support to software like this, and move to AUR maintained by vendor.

**Pull request merged**
