### PR TITLE
fix: Can't pack v23 in obs

### PR DESCRIPTION
**Pull request by 18202781743**
It intrudce in the commit 2b8ee33fe9a9b77053cfa81502089f382322cbf2
  Refact to distinguish the way of v20 and v23, we delay it
tu runtime step instead of compiling step.

### CODE REVIEW

**Comment by kegechen** [comment]
@wyu71

**Review by kegechen — APPROVED** [review]
+1

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by 18202781743** [comment]
@BLumia

**Review by wyu71 — APPROVED** [review]
/+1

**Comment by 18202781743** [comment]
https://pms.uniontech.com/bug-view-218813.html

**Pull request merged**
