### PR TITLE
feat: base master  merge into release/eagle

### PR DESCRIPTION
**Pull request by jeffshuai**
due to use 1070-v20 interfaces of dde-dock in community version-v23

Log: base master  merge into release/eagle

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by max-lvs — APPROVED** [review]

**Review by lzwind — DISMISSED** [review]

**Review by lzwind — APPROVED** [review]

**Pull request merged**
