### PR TITLE
fix: dbus开启系统监视器开关

### PR DESCRIPTION
**Pull request by myk1343**
dbus开启系统监视器开关

Bug: https://pms.uniontech.com/bug-view-211897.html
Log: dbus开启系统监视器开关

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
