### PR TITLE
fix: deepin-system-monitor crashed

### PR DESCRIPTION
**Pull request by 18202781743**
It intrudced in the commit 6e1c14c24b0ec6de1e81807dc7ee531fe2259fda
Missing DBus's assignment of the ObjectPath.

### CODE REVIEW

**Comment by 18202781743** [comment]
@feeengli  @wyu71

**Review by kegechen — APPROVED** [review]

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Comment by 18202781743** [comment]
https://github.com/linuxdeepin/developer-center/issues/5592

**Pull request merged**
