### PR TITLE
fix: 开启浏览器并在系统监视器中选择查看命令所在位置时跳转目录错误

### PR DESCRIPTION
**Pull request by wyu71**
通过进程里的mountinfo和exe文件拼接完整目录

Log: 正确调整目录
Bug: https://pms.uniontech.com/bug-view-183667.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
